name: Github Actions 실행시켜보기

on:
  push:
    branches:
      - develop
# 여러 job은 기본적으로 병렬 수행
jobs:
  # job 식별 id
  My-Deploy-Job:
    # OS
    runs-on: ubuntu-latest
    # 1개의 잡은 여러 순차 스텝들을 가짐
    steps:
      - name: github Repo 파일 가져오기
        uses: actions/checkout@v4

      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 만들기
        run: echo "${{secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: project.jar
          target: /home/ubuntu/chzzkzzal-api/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/chzzkzzal-api/current
            mkdir /home/ubuntu/chzzkzzal-api/current
            mv /home/ubuntu/chzzkzzal-api/tobe/project.jar /home/ubuntu/chzzkzzal-api/current/project.jar
            cd /home/ubuntu/chzzkzzal-api/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/chzzkzzal-api/tobe
        
