name: Deploy‑to‑EC2

on:
  push:
    branches: [ develop ]   # develop 브랜치에 push 될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 저장소 체크아웃
      - name: Checkout source
        uses: actions/checkout@v4

      # 2) JDK 21 설치
      - name: Set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3) Secrets →application.yml 생성
      - name: Generate application.yml from secret
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      # 4) Gradle빌드 (테스트 생략 예시)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5) 산출 JAR이름 통일 (project.jar)
      - name: Rename JAR to project.jar
        run: mv build/libs/*SNAPSHOT.jar project.jar

      # 6) SCP EC2 임시 (tobe) 폴더로 JAR 전송
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/chzzkzzal-api/tobe

      # 7) SSH —EC2에서 서비스 교체 &재시작
      - name: Deploy & restart on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            
            # 디렉터리 정리
            rm -rf /home/ubuntu/chzzkzzal-api/current
            mkdir -p /home/ubuntu/chzzkzzal-api/current
            
            # 새 JAR 이동
            mv /home/ubuntu/chzzkzzal-api/tobe/project.jar /home/ubuntu/chzzkzzal-api/current/project.jar
            rm -rf /home/ubuntu/chzzkzzal-api/tobe
            
            cd /home/ubuntu/chzzkzzal-api/current
            
            # 기존 프로세스 종료 (포트 8080 사용 중이면 kill)
            sudo fuser -k 8080/tcp || true
            
            # 새 프로세스 실행 (mysql 프로필 활성화)
            nohup java -jar project.jar --spring.profiles.active=mysql > output.log 2>&1 &
